---
- name: Install Apache playbook
  hosts: 3.23.88.10	  
  become: yes
  gather_facts: false

  tasks:
  - name: restart apache service
    service:
      name: httpd
      state: restarted
      enabled: yes

