---
- name: Install Apache playbook!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
  hosts: all  
#  become: yes
  gather_facts: false
  vars:
    httpd_packages:
      - httpd
      - python3-mod_wsgi
    apache_test_message: This is a test message
  tasks:
  - name: install httpd packages
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ httpd_packages }}"
    notify: restart apache service
